const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {Pipeline}=require('../src/pipeline.cjs');
test('saved model + saved voice only synthesize new script and run zeroshot',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'avatar-reuse-')),calls=[];
 const client={async api(route,options){calls.push({route,options});if(route.endsWith('/library/model/m'))return {assetId:'m',playerId:'p'};if(route.endsWith('/library/voice/v'))return {speakerId:'s'};if(route.endsWith('/voice')){assert.equal(JSON.parse(options.body).script,'新的口播');return {id:'a'}}if(route.endsWith('/voice-result/a'))return {url:'https://test.myqcloud.com/audio'};if(route.endsWith('/avatar/infer')){assert.equal(options.body.get('playerId'),'p');return {requestId:'i'}}if(route.endsWith('/digital-task/i'))return {event_type:'INFER.SUCCESS',body:{data:'https://test.myqcloud.com/final'}};throw Error('Unexpected '+route)}};
 const engine=new Pipeline({client,root,notify(){},download:async(url,file)=>fs.writeFile(file,'media')});
 try{const s=await engine.create('u',{person:'saved',voice:'saved',modelId:'m',voiceId:'v',script:'新的口播',consent:true});assert.equal((await engine.resume('u',s.id)).status,'completed');assert.equal(calls.filter(x=>x.options?.method==='POST').length,2);assert.ok(!calls.some(x=>/template|\/clone/.test(x.route)));const count=calls.length;await engine.resume('u',s.id);assert.equal(calls.length,count)}finally{await fs.rm(root,{recursive:true,force:true})}
});
test('unavailable or foreign saved asset prevents any creation request',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'avatar-reuse-'));const engine=new Pipeline({root,notify(){},client:{async api(){throw Error('not owned')}}});try{await assert.rejects(engine.create('u',{person:'saved',voice:'saved',modelId:'foreign',voiceId:'v',script:'test',consent:true}));assert.deepEqual(await fs.readdir(root),[])}finally{await fs.rm(root,{recursive:true,force:true})}});
