const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {Pipeline}=require('../src/pipeline.cjs');
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'avatar-pipeline-'));const calls=[];for(const f of ['photo.png','person.mp4','voice.wav','driver.wav'])await fs.writeFile(path.join(root,f),'fixture');
const client={async api(route,options){calls.push({route,options});if(route.endsWith('/library/voice/v'))return {speakerId:'voice'};if(route.endsWith('/template')){assert.equal(options.body.get('audio').name,'driver.wav');return {assetId:'asset',taskId:'template-task'}}if(route.includes('/task/'))return {status:'SUCCESS',results:[{outputType:'mp4',url:'https://test.myqcloud.com/template'}]};if(route.includes('/voice-result/'))return {url:'https://test.myqcloud.com/audio'};if(route.endsWith('/voice/clone'))return {speakerId:'voice'};if(route.endsWith('/voice'))return {id:'audio',url:'https://test.myqcloud.com/audio'};if(route.endsWith('/avatar/clone'))return {assetId:'asset',requestId:'clone'};if(route.endsWith('/avatar/infer'))return {requestId:'final'};if(route.endsWith('/digital-task/clone'))return {event_type:'INFER.SUCCESS',body:{player_id:'player'}};if(route.endsWith('/digital-task/final'))return {event_type:'INFER.SUCCESS',body:{data:'https://test.myqcloud.com/final'}};throw Error(route)}};
const options={driverHash:require('node:crypto').createHash('sha256').update('fixture').digest('hex'),client,root:path.join(root,'tasks'),driver:path.join(root,'driver.wav'),notify(){},interval:1,download:async(url,file)=>{await fs.writeFile(file,url)}};return {root,calls,options,engine:new Pipeline(options)};}
for(const person of ['image'])for(const voice of ['saved'])test(person+' + '+voice+' uses correct stages and only final inference as output',async()=>{const f=await fixture();try{const s=await f.engine.create('u1',{person,voice,voiceId:'v',personPath:path.join(f.root,person==='image'?'photo.png':'person.mp4'),voicePath:path.join(f.root,'voice.wav'),script:'测试',consent:true});const result=await f.engine.resume('u1',s.id);assert.equal(result.status,'completed');const routes=f.calls.map(c=>c.route);assert.equal(routes.includes('/api/avatar-forge/template'),person==='image');assert.equal(routes.includes('/api/avatar-forge/voice/clone'),voice==='clone');assert.equal(await fs.readFile(path.join(f.engine.dir('u1',s.id),'final.mp4'),'utf8'),'https://test.myqcloud.com/final');const count=f.calls.length;await f.engine.resume('u1',s.id);assert.equal(f.calls.length,count);await assert.rejects(f.engine.resume('other-user',s.id));assert.equal((await f.engine.list('u1')).length,1);assert.equal((await f.engine.list('other-user')).length,0)}finally{await fs.rm(f.root,{recursive:true,force:true})}});
test('uncertain submit is persisted and never replayed on restart',async()=>{const f=await fixture();try{const s=await f.engine.create('u1',{person:'image',voice:'saved',voiceId:'v',script:'测试',personPath:path.join(f.root,'photo.png'),voicePath:path.join(f.root,'voice.wav'),consent:true});let calls=0;f.options.client.api=async()=>{calls++;throw Error('network')};const result=await f.engine.resume('u1',s.id);assert.equal(result.status,'uncertain');const resumed=new Pipeline(f.options);assert.equal((await resumed.resume('u1',s.id)).status,'uncertain');assert.equal(calls,1)}finally{await fs.rm(f.root,{recursive:true,force:true})}});

test('new video-source jobs are rejected without provider calls',async()=>{const f=await fixture();try{await assert.rejects(f.engine.create('u1',{person:'video',voice:'audio',consent:true}));assert.equal(f.calls.length,0)}finally{await fs.rm(f.root,{recursive:true,force:true})}});
