const paths={plus:'M12 5v14M5 12h14',history:'M3 11a9 9 0 1 1 2.6 7M3 4v7h7M12 7v5l3 2',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 21v-2a8 8 0 0 1 16 0v2',login:'M9 4H4v16h5M13 8l4 4-4 4M8 12h13',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',upload:'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5',image:'M3 3h18v18H3ZM3 16l6-6 6 7 3-4 3 3M17 7h.01',video:'M3 5h12v14H3ZM15 9l6-3v12l-6-3',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0ZM5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8',reset:'M3 10a9 9 0 1 1 1 7M3 3v7h7',play:'m8 4 12 8-12 8Z',close:'m6 6 12 12M6 18 18 6',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6ZM8 12l3 3 5-6',check:'m5 12 4 4L19 6'};
document.querySelectorAll('[data-icon]').forEach(el=>{const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('fill','none');s.setAttribute('stroke','currentColor');s.setAttribute('stroke-width','1.6');s.setAttribute('stroke-linecap','round');s.setAttribute('stroke-linejoin','round');s.setAttribute('aria-hidden','true');const p=document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',paths[el.dataset.icon]||paths.plus);s.append(p);el.append(s);});
const $=id=>document.getElementById(id);
let person='image',voice='clone',personFile=null,voiceFile=null,personUrl=null,voiceUrl=null,timer=null,toastTimer=null;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
function notice(title,text){$('notice-title').textContent=title;$('notice-text').textContent=text;$('notice').showModal()}
let currentUser=null;
function renderAccount(user){currentUser=user;const label=$('login').children[1];label.replaceChildren();label.append(document.createTextNode(user?user.displayName:'登录 LycheeAILab'));const sub=document.createElement('small');sub.textContent=user?'已登录 · 点击退出':'同步账户与制作记录';label.append(sub)}
$('login').onclick=async()=>{
 if(!window.avatarAuth)return notice('请使用桌面客户端登录','浏览器预览不接收设备凭据。请从 Avatar Forge 桌面客户端发起 Lab 登录。');
 if(timer)return toast('请先等待当前流程演示结束。');
 if(currentUser&&!confirm('退出当前 Lab 账户？'))return;
 $('login').disabled=true;
 try{const result=await window.avatarAuth[currentUser?'logout':'login']();if(!result.ok)throw Error(result.error);if(currentUser)renderAccount(null);else toast(result.data.message)}catch(error){toast(error.message)}finally{$('login').disabled=false}
};
if(window.avatarAuth){window.avatarAuth.onChange(value=>{if(value.error)toast(value.error);else{renderAccount(value.user);toast(value.user?'Lab 登录成功':'已退出登录')}});window.avatarAuth.status().then(result=>{if(result.ok)renderAccount(result.data.user);else toast(result.error)}).catch(()=>toast('无法读取桌面登录状态，请重新启动客户端'));}
$('update').onclick=()=>notice('客户端预览版','当前为 0.1.1 本地交互预览，尚未配置正式更新源。确认界面与完整生成链路后，再提供安装包和自动更新。');
$('close-dialog').onclick=$('acknowledge').onclick=()=>$('notice').close();
$('notice').addEventListener('click',e=>{if(e.target===$('notice')){const r=$('notice').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('notice').close()}});
function steps(){return [person==='saved'?'复用已克隆模特':person==='image'?'准备人物动作模板':'检查人物视频',voice==='saved'?'使用已有音色合成口播':voice==='clone'?'克隆音色与合成口播':'准备目标口播音频',person==='saved'?'跳过数字人克隆':'快速克隆数字人','生成最终口播视频']}
function renderProgress(active=-1){$('progress').replaceChildren(...steps().map((text,i)=>{const li=document.createElement('li'),num=document.createElement('span'),label=document.createElement('b'),status=document.createElement('small');num.textContent=i<active?'✓':String(i+1);label.textContent=text;label.style.fontWeight='400';status.textContent=i<active?'演示完成':i===active?'模拟处理中':'待开始';li.className=i<active?'is-done':i===active?'is-current':'';li.append(num,label,status);return li}));}
function stop(){clearInterval(timer);timer=null;renderProgress();$('result').hidden=true;$('progress-status').textContent='尚未开始';$('simulate').disabled=false}
function setPerson(mode){stop();person=mode;personFile=null;$('person-file').value='';if(personUrl)URL.revokeObjectURL(personUrl);personUrl=null;$('portrait').hidden=$('person-player').hidden=true;$('portrait').removeAttribute('src');$('person-player').pause();$('person-player').removeAttribute('src');$('person-player').load();$('empty').hidden=false;$('stage-label').hidden=true;$('preview-state').textContent='等待素材';$('person-file').accept=mode==='image'?'image/png,image/jpeg,image/webp':'video/mp4,video/quicktime';$('person-name').textContent=mode==='image'?'点击选择或拖入人物图片':'点击选择或拖入人物视频';$('person-help').textContent=mode==='image'?'正面、清晰的单人照 · JPG / PNG / WebP · ≤15 MB':'清晰、稳定的单人出镜视频 · MP4 / MOV · ≤600 MB';$('person-route').textContent=mode==='image'?'图片将用于制作动作模板，再克隆数字人。':'直接用视频克隆数字人，无需再生成动作模板。';document.querySelectorAll('[data-person]').forEach(b=>{b.classList.toggle('is-selected',b.dataset.person===mode);b.setAttribute('aria-pressed',String(b.dataset.person===mode))});renderProgress()}
function setVoice(mode){stop();voice=mode;voiceFile=null;$('voice-file').value='';if(voiceUrl)URL.revokeObjectURL(voiceUrl);voiceUrl=null;$('voice-player').pause();$('voice-player').removeAttribute('src');$('voice-player').load();$('voice-player').hidden=true;$('voice-name').textContent=mode==='clone'?'上传参考声音':'上传完整口播音频';$('voice-help').textContent=`WAV / MP3 · ≤${mode==='clone'?15:100} MB`;$('voice-route').textContent=mode==='clone'?'使用这段声音的音色，朗读下方文案。':'直接驱动数字人，不再克隆音色或合成语音。';$('script-section').hidden=mode==='audio';document.querySelectorAll('[data-voice]').forEach(b=>{b.classList.toggle('is-selected',b.dataset.voice===mode);b.setAttribute('aria-pressed',String(b.dataset.voice===mode))});renderProgress()}
document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>setPerson(b.dataset.person));document.querySelectorAll('[data-voice]').forEach(b=>b.onclick=()=>setVoice(b.dataset.voice));
function accept(file,kind){if(!file)return;const isPerson=kind==='person',limit=isPerson?(person==='image'?15:600):(voice==='clone'?15:100);const ext=file.name.split('.').pop().toLowerCase();const allowed=isPerson?(person==='image'?['jpg','jpeg','png','webp']:['mp4','mov']):['wav','mp3'];if(!allowed.includes(ext)||file.size>limit*1024*1024||file.size===0){toast(`请选择支持的非空文件，大小不超过 ${limit} MB`);return}stop();if(isPerson){personFile=file;if(personUrl)URL.revokeObjectURL(personUrl);personUrl=URL.createObjectURL(file);$('person-name').textContent=file.name;$('empty').hidden=true;const el=$(person==='image'?'portrait':'person-player');el.src=personUrl;el.hidden=false;$('stage-label').hidden=false;$('preview-state').textContent='素材已就绪';}else{voiceFile=file;if(voiceUrl)URL.revokeObjectURL(voiceUrl);voiceUrl=URL.createObjectURL(file);$('voice-name').textContent=file.name;$('voice-player').src=voiceUrl;$('voice-player').hidden=false;}}
['person','voice'].forEach(kind=>{$(kind+'-file').onchange=e=>accept(e.target.files[0],kind);const drop=$(kind+'-drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('is-dragging')};drop.ondragleave=()=>drop.classList.remove('is-dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('is-dragging');accept(e.dataTransfer.files[0],kind)}});
[$('portrait'),$('person-player'),$('voice-player')].forEach(el=>el.addEventListener('error',()=>toast('当前素材无法预览，请检查文件格式或编码。')));
$('script').oninput=()=>$('script-count').textContent=`${Array.from($('script').value).length} 字`;
$('simulate').onclick=()=>{if(!personFile||!voiceFile||(voice==='clone'&&!$('script').value.trim()))return toast('请先选择人物、声音，并填写需要朗读的文案。');if(!$('consent').checked)return toast('请先确认素材使用授权。');stop();let active=0;renderProgress(active);$('simulate').disabled=true;$('progress-status').textContent='流程模拟 · 不调用服务';timer=setInterval(()=>{active++;renderProgress(active);if(active===4){clearInterval(timer);timer=null;$('result').hidden=false;$('progress-status').textContent='演示结束';$('simulate').disabled=false}},1100)};
$('reset').onclick=()=>{if(document.querySelector('.af-form').classList.contains('is-busy'))return toast('请先暂停当前制作，再重置输入。');if((personFile||voiceFile||$('script').value)&&!confirm('清空当前素材选择和文案？原始文件不会删除。'))return;setPerson('image');setVoice('clone');$('script').value='';$('script-count').textContent='0 字';$('consent').checked=false};
function page(name){$('studio').hidden=name!=='studio';$('history').hidden=name!=='history';$('breadcrumb').textContent=name==='studio'?'新建制作':'制作历史';document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('is-selected',b.dataset.page===name))}document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));$('back-studio').onclick=()=>page('studio');
window.addEventListener('beforeunload',()=>{if(personUrl)URL.revokeObjectURL(personUrl);if(voiceUrl)URL.revokeObjectURL(voiceUrl)});renderProgress();
